version: "3"
services:
  movie-container:
    image: movie-portal
    ports:
      - "8081:8081"
    networks:
      - movie-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - movie-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movieportal  

networks:
  movie-mysql:
