version: "3"
services:
  movie-container:
    image: movie-portal
    ports:
      - "8081:8081"
    networks:
      - movie-mysql
    depends_on:
      - mysqldb:
          condition: service_healthy
 
  mysqldb:
    image: mysql:8
    networks:
      - movie-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movieportal
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10

networks:
  movie-mysql:
