
server:
  port: 8081
  #contextPath: /swagger2-movieportal

spring:
  datasource:
    #url: jdbc:mysql://mysqldb/movieportal?serverTimezone=GMT-6  #mysqldb is docker instance
    url: jdbc:mysql://localhost:3306/movieportal?serverTimezone=GMT-6
    password: root #non-prod code, change this to your database username
    username: root #non-prod code, change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
